services:
  backend:
    build: ./backend
    ports:
      - "0.0.0.0:5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chess
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5001
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    working_dir: /app
    depends_on:
      - backend

volumes:
  mongo_data:
